project:
  type: website

website:
  title: "Wages in USA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - model.qmd
      - graphs.qmd
      - sources.qmd
      - about.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true


